version: '2'
services:
    dematnotes-app:
        image: dematnotes
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dematnotes-postgresql:5432/DematNotes
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dematnotes-postgresql:
        extends:
            file: postgresql.yml
            service: dematnotes-postgresql
